apiVersion: v1
kind: Service
metadata:
  name: psieczkole-service
spec:
  type: NodePort
  selector:
    app: psieczkole-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080